name: cache

on:
  workflow_dispatch:

jobs:
  test_cache:
    name: a job to test cache 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      
      - uses: actions/cache@v4.3.0
        id: generateCache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - run: pip install -r requirements.txt
      
      - name: we can confirm the cache
        if: steps.generateCache.outputs.cache-hit == 'true'
        run: echo "cache is found"
